export { default as Loader } from "./Loader";
export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as News } from './News';
export { default as Cryptocurrencies } from './Cryptocurrencies';
export { default as Homepage } from './Homepage';
export { default as LoginForm } from './LoginForm';
export { default as SignupForm } from './SignupForm';
export { default as CryptoDetails } from "./CryptoDetails";
export { default as Services } from "./Services";
// export { default as Transactions } from "./Transactions";